version: '3'
services:
  redis:
    image: redis
  rtq-worker:
    image: openanalytics/rtq-client
    build: rtq-client
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    depends_on:
        - redis
  rtq-producer:
    image: openanalytics/rtq-client
    build: rtq-client
    environment:
        - REDIS_HOST=redis
        - REDIS_PORT=6379
    depends_on:
        - redis 
  
